README.md, rococo/data/base.py, rococo/data/surrealdb.py, rococo/models/email.py, rococo/models/versioned_model.py, rococo/repositories/__init__.py, rococo/repositories/base_repository.py, tests/base_repository_test.py
- 40e2780  Updated the response in DpAdapter.
- 38c4f2e - Updated repostory usage. - Updated class modifiers. - Added usage in Readme.md.
- dbd3bcd - Addition of base repository. - Addition of test cases. - Addition of base wrapper.
- 13cfef0 - Added query builder for get and get many. - Added email model to be used.
FPM-866 https://freelancedevelopercoach.atlassian.net/browse/FPM-866
=> Caeser1996 base repositories

README.md, rococo/data/base.py, rococo/data/surrealdb.py, rococo/models/email.py, rococo/models/versioned_model.py, rococo/repositories/__init__.py, rococo/repositories/base_repository.py, tests/base_repository_test.py
- 40e2780  Updated the response in DpAdapter.
- 38c4f2e - Updated repostory usage. - Updated class modifiers. - Added usage in Readme.md.
- dbd3bcd - Addition of base repository. - Addition of test cases. - Addition of base wrapper.
- 13cfef0 - Added query builder for get and get many. - Added email model to be used.
FPM-866 https://freelancedevelopercoach.atlassian.net/browse/FPM-866
=> Updated the response in DpAdapter.

rococo/repositories/base_repository.py, setup.py, tests/base_repository_test.py
Added Rabbit adapter to BaseRepository constructor that allows optional queueing of message when doing .save 
Added test (I think the test can be improved, I have very little experience with Mock)
[FPM-873](https://freelancedevelopercoach.atlassian.net/browse/FPM-873)
- [ done] I have performed a self-review of my code
=> Matovolador fpm 873 v2

rococo/messaging/__init__.py, rococo/messaging/base.py, rococo/messaging/rabbitmq.py, rococo/messaging/sqs.py, rococo/repositories/base_repository.py, setup.py, tests/base_repository_test.py
Changed RabbitMQ for abstract Connection class to support that and SQS
Bumped version
[FPM-873](https://freelancedevelopercoach.atlassian.net/browse/FPM-873)
- [ done] I have performed a self-review of my code
=> Matovolador fpm 873 v3

README.md, rococo/messaging/__init__.py, rococo/messaging/base.py, setup.py
Added abstract class BaseServiceProcessor to process message data from RabbitMQ and SQS
[FPM-874](https://freelancedevelopercoach.atlassian.net/browse/FPM-874)
- [done ] I have performed a self-review of my code
=> Matovolador fpm 874

.circleci/config.yml, rococo/messaging/base.py, setup.py
added missing argument to 'process' method
https://freelancedevelopercoach.atlassian.net/jira/software/c/projects/ROC/issues/ROC-11
=> [ROC-11] - added missing argument to 'process' method

setup.py
fixed broken tests suite
https://freelancedevelopercoach.atlassian.net/jira/software/c/projects/ROC/issues/ROC-11?filter=myopenissues
=> [ROC-11] - fixed broken tests suite

requirements.txt, rococo/config/__init__.py, rococo/config/config.py, setup.py, tests/config_test.py
- Created a config class that allows to load from a .toml file, and/or use a .env file.
- Created tests for Config
[ROC-17](https://freelancedevelopercoach.atlassian.net/browse/ROC-17)
- [done] I have performed a self-review of my code
=> Matovolador roc 17

rococo/messaging/__init__.py, rococo/messaging/base.py, rococo/messaging/rabbitmq.py, rococo/messaging/sqs.py, rococo/models/__init__.py, rococo/models/email.py, rococo/models/login_method.py, rococo/models/organization.py, rococo/models/otp_method.py, rococo/models/person.py, rococo/models/person_organization_role.py, rococo/models/versioned_model.py, rococo/repositories/__init__.py, rococo/repositories/base_repository.py, setup.py, tests/base_repository_test.py, tests/config_test.py, tests/model_test.py
- Corrected linting warnings
[ROC-18](https://freelancedevelopercoach.atlassian.net/browse/ROC-18)
- [ done] I have performed a self-review of my code
=> linting corrections

setup.py
- version bumping -> 0.1.19
- [ROC-16 - improving code-health of rococo package](https://freelancedevelopercoach.atlassian.net/browse/ROC-16)
- [ x ] I have performed a self-review of my code
=> version bumping -> 0.1.19

rococo/config/config.py, rococo/data/__init__.py, rococo/messaging/rabbitmq.py, rococo/messaging/sqs.py, rococo/models/versioned_model.py, rococo/repositories/base_repository.py, rococo/repositories/surreal_db_repository.py, setup.py, tests/base_repository_test.py, tests/surreal_db_repository_test.py
- Removed PEP warnings and errors
https://freelancedevelopercoach.atlassian.net/browse/ROC-19
=> Matovolador roc 19

.gitignore, requirements.txt, rococo/emailing/__init__.py, rococo/emailing/base.py, rococo/emailing/config.py, rococo/emailing/enums.py, rococo/emailing/factory.py, rococo/emailing/mailjet.py, rococo/emailing/ses.py, setup.py
A generic codebase is added for email providers for plug n play with consuming services
https://freelancedevelopercoach.atlassian.net/browse/FPM-881
=> [FPM-881] - Email service

.gitignore, requirements.txt, rococo/emailing/__init__.py, rococo/emailing/base.py, rococo/emailing/config.py, rococo/emailing/enums.py, rococo/emailing/factory.py, rococo/emailing/mailjet.py, rococo/emailing/ses.py, setup.py
A generic codebase is added for email providers for plug n play with consuming services
https://freelancedevelopercoach.atlassian.net/browse/FPM-881
=> [FPM-881] - Merging Email Service into main

rococo/models/versioned_model.py, setup.py
- Use UUID instead of str for ids
https://freelancedevelopercoach.atlassian.net/browse/ROC-20
=> Matovolador roc 20

README.md, setup.py
- updated readme
https://freelancedevelopercoach.atlassian.net/browse/ROC-20
=> updated readme

README.md
- corrected type
https://freelancedevelopercoach.atlassian.net/browse/ROC-20
=> correct type

rococo/models/versioned_model.py, setup.py
- use field
https://freelancedevelopercoach.atlassian.net/browse/ROC-21
=> Matovolador roc 21

rococo/models/versioned_model.py, setup.py, tests/model_test.py
- Fixed the `from_dict` method of `VersionedModel`.
- Add unit tests for `from_dict` method.
BRET-8
=> [FIX] Fix from_dict method and add unit test

rococo/models/versioned_model.py, setup.py, tests/model_test.py
Fix as_dict method to include only model fields
BRET-8
=> [FIX] Fix as_dict method to filter attributes that are not model fields

rococo/config/config.py, rococo/data/surrealdb.py, rococo/models/login_method.py, setup.py
- Add `get_var_as_list` to `Config` class.
- Update `save` implementation to use `db.create` function of SurrealDB SDK.
- Change `email` field on LoginMethod to `email_id`.
BRET-14
=> Update save implementation in SurrealDB Adapter

rococo/data/base.py, rococo/data/surrealdb.py, rococo/models/versioned_model.py, rococo/repositories/base_repository.py, setup.py, tests/base_repository_test.py
- Add `latest` attribute to `VersionedModel` and set existing entities' `latest` attribute to `false` on save.
- Use `prepare_for_save` to set `entity_id`, `version`, `previous_version` and `changed_by_id` fields.
- Update `delete` implementation to set `active=false` and save.
- Update `get_` implementations to support different data types in conditions and only query `active` and `latest` results.
- BRET-14
=> Update save and delete implementation for SurrealDB

rococo/data/surrealdb.py, rococo/models/versioned_model.py, rococo/repositories/base_repository.py, rococo/repositories/surreal_db_repository.py, setup.py, tests/base_repository_test.py, tests/surreal_db_repository_test.py
- Refactor SurrealDbRepository to use BaseRepository methods
- Update save and delete implementation to use `_audit` tables instead of `latest`
ROC-22
=> [ROC-22] Refactor base repositories and update save implementation to use audit tables

README.md, rococo/data/base.py, rococo/data/surrealdb.py, rococo/models/email.py, rococo/models/login_method.py, rococo/models/organization.py, rococo/models/otp_method.py, rococo/models/person.py, rococo/models/person_organization_role.py, rococo/models/versioned_model.py, rococo/repositories/base_repository.py, rococo/repositories/surreal_db_repository.py, tests/base_repository_test.py, tests/surreal_db_repository_test.py
- Implement relationship modelling in VersionedModel, BaseRepository, SurrealDbRepository and SurrealDbAdapter to use record links
- BRET-27
=> [BRET-27] Update relation modelling for many to 1 relations

rococo/repositories/surreal_db_repository.py, setup.py
- Add `unrelate` method to SurrealDbRepository
BRET-27
=> [BRET-27] Add unrelate method to SurrealDbRepository

rococo/models/versioned_model.py, setup.py
- Import models module from rococo if not exists in project.
N/A
=> [FIX] Fix model import issues

rococo/models/versioned_model.py, rococo/repositories/surreal_db_repository.py, setup.py
- Fix a bug with importing
- Implement querying IDs by list
N/A
=> Fix a bug with import & implement querying IDs by list

rococo/models/otp_method.py
- add default value for otpmethod model person field
https://freelancedevelopercoach.atlassian.net/browse/BRET-39
=> set a default

README.md, pull_request_template.md, setup.py
=> Sinisarudan roc 13

setup.py
=> version bumping

rococo/config/config.py, setup.py
- optionally log version string. defaults to True
https://freelancedevelopercoach.atlassian.net/browse/ROC-29
=> Matovolador roc 29

setup.py
- added pymysql to install requires
-
=> Matovolador bret 102

rococo/models/versioned_model.py, rococo/repositories/mysql/mysql_repository.py, setup.py
- Strip dashes from all UUID fields before saving
N/A
=> [FIX] Strip dashes from all UUID fields before saving

rococo/data/mysql.py, rococo/repositories/mysql/mysql_repository.py, setup.py
Add support for LIMIT and OFFSET in MySqlRepository.get_many method
ROC-32
N/A
=> [ROC-32] Add support for LIMIT and OFFSET in MySqlRepository.get_many method

rococo/messaging/rabbitmq.py, setup.py
Add support for real-time consume config file and EXIT_WHEN_FINISHED
ROC-35
=> [ROC-35] Add support for real-time consume config file and EXIT_WHEN_FINISHED

rococo/messaging/sqs.py, setup.py
- Update SQS messaging adapter to get or create queue if not exists
CPC-415
=> Update SQS messaging adapter to get or create queue if not exists

rococo/messaging/sqs.py, setup.py
- Add support for EXIT_WHEN_FINISHED to SqsMessaging Adapter
- CPC-415
=> Add support for EXIT_WHEN_FINISHED to SqsMessaging Adapter

rococo/config/config.py, rococo/data/mysql.py, rococo/repositories/mysql/mysql_repository.py, setup.py
- fix insert in audit table query
- bumped version
- return type fixes
- code reformatting
ROC-37, https://freelancedevelopercoach.atlassian.net/browse/ROC-37
=> Deepak roc 37

rococo/config/config.py, rococo/data/mysql.py, rococo/repositories/mysql/mysql_repository.py, setup.py
- fix insert in audit table query
- bumped version
- return type fixes
- code reformatting
ROC-37, https://freelancedevelopercoach.atlassian.net/browse/ROC-37
=> Merge main to staging

rococo/auth/__init__.py, rococo/auth/tokens.py, setup.py
- added common authorization token managment functions
- bump version
https://freelancedevelopercoach.atlassian.net/browse/ROC-40
=> Matovolador roc 40

rococo/emailing/mailjet.py, setup.py
Add support for CC and BCC email addresses for Mailjet
ROC-46
=> [ROC-46] Add support for CC and BCC email addresses for Mailjet

requirements.txt, rococo/emailing/config.py, setup.py
=> [EV-1886] - give pydantic version as range for child images to work with

rococo/models/surrealdb/surreal_versioned_model.py, rococo/models/versioned_model.py
Use UUID generator function instead of uuid4
ROC-39
=> [ROC-39] Use UUID generator function instead of uuid4

requirements.txt, rococo/emailing/config.py, rococo/models/surrealdb/surreal_versioned_model.py, rococo/models/versioned_model.py, rococo/repositories/mysql/mysql_repository.py, rococo/repositories/surrealdb/surreal_db_repository.py, setup.py, tests/model_test.py, tests/surreal_db_repository_test.py
Fix a bug with filtering None values in MySqlRepository
ROC-53
=> [ROC-53] Fix a bug with filtering None values in MySqlRepository

setup.py
=> update rococo version

.github/workflows/publish-log4brains.yml, .log4brains.yml, docs/decisions/template.md
Added log4brains configuration files and GitHub action
[ROC-51](https://freelancedevelopercoach.atlassian.net/browse/ROC-51)
see [Log4Brains](https://github.com/thomvaill/log4brains?tab=readme-ov-file#log4brains-) demos
=> ROC-51 use log4brains for decision log tracking

.github/workflows/publish-log4brains.yml, docs/decisions/index.md
- rebuild the decision log website on relevant changes only
- fixed relative URLs in the decision log website
- add a badge with decision count to the decision website index
[ROC-51](https://freelancedevelopercoach.atlassian.net/browse/ROC-51)
=> ROC-51 amend decision log build

README.md, docs/decision-log-overview.md, docs/decisions/20240610-use-log4brains-to-manage-decision-log.md, docs/decisions/index.md
- added decision log overview document
- updated decision log home page
- updated decision status
[ROC-51](https://freelancedevelopercoach.atlassian.net/browse/ROC-51)
=> ROC-51 update docs - decision log overview + misc

rococo/messaging/rabbitmq.py, setup.py
Add resilience to RabbitMQ adapter
ROC-56
=> [ROC-56] Add resilience to RabbitMQ adapter

rococo/models/versioned_model.py, setup.py
Add model validation and experimental type checking
S2R-2736
=> [S2R-2736] Add model validation and experimental type checking

rococo/models/versioned_model.py, setup.py
Add support for enum casting in validate method
S2R-2740
=> [S2R-2740] Add support for enum casting in validate method

README.md, rococo/messaging/rabbitmq.py, rococo/models/organization.py, setup.py
- Update README.md
- Remove join_fields documentation for MySQL adapter
- Add instructions for email-transmitter service
- Make messages sent using RabbitMqAdapter persistent.
N/A
=> [UPD] Update README to remove join_fields documentation & add instructions for email-transmitter service

README.md, rococo/migrations/mysql/__init__.py, rococo/migrations/mysql/cli.py, rococo/migrations/mysql/migration.py, rococo/migrations/mysql/migration_template.py, rococo/migrations/mysql/run.py, setup.py
Implement MySQL migrations module
VEY-1
=> [VEY-1] Implement MySQL migrations module

rococo/migrations/mysql/cli.py, setup.py
Update mysql migrations CLI to look for environment variables in environment first
VEY-1
=> [VEY-1] Update mysql migrations CLI to look for environment variables in environment first

rococo/repositories/mysql/mysql_repository.py, setup.py
- Fix a bug in MySQL repository get_many method
VEY-1
=> [FIX] Fix a bug in MySQL repository get_many method

README.md
Removed mentions of SecondSight and secondsight.ai from the code
[ROC-59](https://freelancedevelopercoach.atlassian.net/browse/ROC-59)
=> [ROC-59] Get rid of SecondSight mentions

README.md, requirements.txt, rococo/data/mysql.py, setup.py
Fix string interpolation in get_ functions of MySQL adapter
S2R-2802
=> [S2R-2802] Fix string interpolation in get_ functions of MySQL adapter

rococo/models/versioned_model.py, setup.py
Fix a breaking change in versioned model class
S2R-2802
=> [S2R-2802] Fix a breaking change in versioned model class

rococo/migrations/mysql/migration.py, setup.py
Fix a bug in migrations lib
N/A
=> [FIX] Fix a bug in migrations lib

requirements.txt, rococo/data/mysql.py, rococo/plugins/pooled_connection.py, setup.py
Add plugin and support for Pooled DB connections in Flask
N/A
=> Add plugin and support for Pooled DB connections in Flask

rococo/data/mysql.py, rococo/plugins/pooled_connection.py, setup.py
Update PooledDB plugin and adapter to handle database connections for Flask
N/A
=> Update PooledDB plugin and adapter to handle database connections for Flask

setup.py
Add init to migrations.common module
N/A
=> [FIX] Add init to migrations.common module

rococo/repositories/mongodb/__init__.py, setup.py
Fix: add missing MongoDbRepository import
=> Fix: add missing MongoDbRepository import

requirements.txt, setup.py, specs/models.md, specs/repositories.md, specs/services.md, specs/sql-migrations.md
* Updated surrealdb version to 1.0.4, and all it's dependencies to corresponding versions
[ROC-66](https://freelancedevelopercoach.atlassian.net/browse/ROC-66)
=> Upgrade surrealdb to the latest version 1.0.4

rococo/data/mongodb.py, rococo/repositories/mongodb/mongodb_repository.py, setup.py, tests/mongodb_repository_test.py
* Fixed wrong versioning strategy on save which tried to replace previous versions
* Fix audit records creation
* Make save/create/delete methods consistent with get_one, get_many - they now require collection_name and index
* Split "data" extra into multiple ones - for each supported db
https://freelancedevelopercoach.atlassian.net/browse/ROC-69
https://freelancedevelopercoach.atlassian.net/browse/ROC-70
=> [ROC-70] Bugfixing Mongodb adapter and repository

rococo/data/__init__.py, rococo/repositories/mongodb/mongodb_repository.py, setup.py
* Removed redundant unset_old() method in MongoDB repository save - which was breaking versioning logic
https://freelancedevelopercoach.atlassian.net/browse/ROC-70
=> [ROC-70] Fix save method in MongoDB adapter

rococo/repositories/mongodb/mongodb_repository.py, setup.py
* Fix delete function in mongo repository
[ROC-74](https://freelancedevelopercoach.atlassian.net/browse/ROC-74)
=> [ROC-74] Fix delete function in mongo repository

rococo/messaging/sqs.py, setup.py
* Use 2 new variables from consume_config in Sqs adapter: LISTEN_INTERVAL and VISIBILITY_TIMEOUT
[ROC-85](https://freelancedevelopercoach.atlassian.net/browse/ROC-85)
=> [ROC-85] v1.1.5 Pass visibility timeout and listen interval to sqs messaging adapter

rococo/messaging/sqs.py, setup.py
* Use int() parameters for boto3 in sqs messaging adapter
[ROC-85](https://freelancedevelopercoach.atlassian.net/browse/ROC-85)
=> [bugfix] v1.1.6 Use proper boto3 parameter types

requirements.txt, rococo/faxing/base.py, rococo/faxing/config.py, rococo/faxing/enums.py, rococo/faxing/factory.py, rococo/faxing/ifax.py, setup.py, tests/fixtures/config.json, tests/test_faxing.py
This PR adds fax support to rococo framework using similar pattern in `emailing` module and `ifax` integration.
[ALE-211](https://freelancedevelopercoach.atlassian.net/browse/ALE-211)
=> Add `faxing` module with `ifax` support

requirements.txt, rococo/faxing/base.py, rococo/faxing/config.py, rococo/faxing/enums.py, rococo/faxing/factory.py, rococo/faxing/ifax.py, setup.py, tests/fixtures/config.json, tests/test_faxing.py
This PR adds fax support to rococo framework using similar pattern in `emailing` module and `ifax` integration.
[ALE-211](https://freelancedevelopercoach.atlassian.net/browse/ALE-211)
=>  Add faxing module with ifax support 

rococo/emailing/base.py, rococo/emailing/mailjet.py, rococo/emailing/ses.py, setup.py, tests/test_mailjet_addresses.py
* [emailing] Support for email and name in recipient list
* [emailing] Added new functions: create_contact, remove_contact
* [emailing] Unit tests for recipient list parser
[ROC-87](https://freelancedevelopercoach.atlassian.net/browse/ROC-87)
=> [ROC-87] v1.1.8, Mailjet improvements
